/**
 * Mock 数据定义
 *
 * 数据模式下所有预定义的 API 响应数据集中存放于此。
 * 修改此文件后重启应用即可生效。
 *
 * 每条数据尽可能覆盖该模型的不同状态/类型组合。
 *
 * key 格式："METHOD /path"（不含 query params，method 为实际 HTTP 方法）
 * value 为完整的 API 响应 { code=200, message, data }
 */
import type { MockResponse } from './dev'
import { MOCK_IMAGE_BASE_URL } from '@/config/env'

export const mockData: Record<string, MockResponse> = {
  /* ===================== 身份与资料 ===================== */

  'GET /identity/me/profile': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10001',
      nickname: '测试用户',
      avatar: null,
      gender: 'male',
      birthday: '2000-01-15',
      signature: '热爱运动与桌游',
      interestTags: ['运动健身', '桌游聚会'],
      kind: 'personal',
      reputationScore: 100,
    },
  },

  'PATCH /identity/me/profile': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10001',
      nickname: '测试用户',
      avatar: null,
      gender: 'male',
      birthday: '2000-01-15',
      signature: '热爱运动与桌游',
      interestTags: ['运动健身', '桌游聚会'],
      kind: 'personal',
      reputationScore: 100,
    },
  },

  /* 商家：已通过审核 + 资质完整 */
  'GET /identity/me/merchant-profile': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10001',
      avatar: null,
      nickname: '趣聚咖啡',
      merchantName: '趣聚咖啡（北京）有限公司',
      interestedActivityFields: ['美食餐饮', '城市探索'],
      accountStatus: 'active',
      qualificationStatus: 'approved',
      qualification: {
        status: 'approved',
        submittedAt: '2026-01-10T08:00:00Z',
        reviewedAt: '2026-01-12T10:30:00Z',
        rejectReason: null,
        licenseImageUrls: [MOCK_IMAGE_BASE_URL + '/400/300?random=1'],
      },
    },
  },

  'PATCH /identity/me/merchant-profile': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10001',
      avatar: null,
      nickname: '趣聚咖啡',
      merchantName: '趣聚咖啡（北京）有限公司',
      interestedActivityFields: ['美食餐饮', '城市探索'],
      accountStatus: 'active',
      qualificationStatus: 'approved',
      qualification: {
        status: 'approved',
        submittedAt: '2026-01-10T08:00:00Z',
        reviewedAt: '2026-01-12T10:30:00Z',
        rejectReason: null,
        licenseImageUrls: [MOCK_IMAGE_BASE_URL + '/400/300?random=1'],
      },
    },
  },

  'GET /identity/interest-tags': {
    code: 200,
    message: 'For Super Earth!',
    data: [
      { name: '运动健身' },
      { name: '户外徒步' },
      { name: '桌游聚会' },
      { name: '学习交流' },
      { name: '公益活动' },
      { name: '城市探索' },
      { name: '美食餐饮' },
      { name: '摄影采风' },
    ],
  },

  'GET /identity/nicknames/availability': {
    code: 200,
    message: 'For Super Earth!',
    data: { nickname: '', available: true },
  },

  'POST /identity/me/merchant-qualification': {
    code: 200,
    message: 'For Super Earth!',
    data: {},
  },

  'POST /identity/media/avatar': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      mediaId: '9001',
      signedUrl: MOCK_IMAGE_BASE_URL + '/200',
      contentType: 'image/jpeg',
      fileName: 'avatar.jpg',
      sizeBytes: 102400,
      uploadedAt: '2026-07-01T12:00:00Z',
      usage: 'avatar',
    },
  },

  'POST /identity/media/license': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      mediaId: 'license-9001',
      signedUrl: MOCK_IMAGE_BASE_URL + '/400/300?random=license',
      contentType: 'image/jpeg',
      fileName: 'merchant-license.jpg',
      sizeBytes: 204800,
      uploadedAt: '2026-07-01T12:00:00Z',
      usage: 'merchantLicense',
    },
  },

  /* ===================== 活动 ===================== */

  /*
   * runtimeStatus 全覆盖: registering | registrationClosed | ongoing | ended | notStarted | takenDown
   * reviewStatus: approved | pending | rejected
   * feeAmount: 0.0 (免费) | 正整数 (付费)
   * coverImage: null | 有图片
   * registeredCount: 0 | 部分 | 满员
   */
  'GET /activities/mine': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2001',
          title: '周末羽毛球友谊赛',
          capacity: 16,
          startAt: '2026-07-05T14:00:00Z',
          endAt: '2026-07-05T17:00:00Z',
          location: {
            address: '海淀区体育馆羽毛球馆',
            city: '北京',
            placeName: '海淀体育馆',
            point: { longitude: 116.347, latitude: 39.972 },
          },
          registeredCount: 12,
          tags: ['运动健身'],
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
          coverImage: null,
          feeAmount: 30.0,
        },
        {
          activityId: '2002',
          title: '桌游之夜——三国杀专场',
          capacity: 8,
          startAt: '2026-07-12T19:00:00Z',
          endAt: '2026-07-12T22:00:00Z',
          location: {
            address: '五道口桌游吧',
            city: '北京',
            placeName: '五道口桌游吧',
            point: { longitude: 116.337, latitude: 39.982 },
          },
          registeredCount: 8,
          tags: ['桌游聚会'],
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
          feeAmount: 50.0,
        },
        {
          activityId: '2003',
          title: '公益植树活动',
          capacity: 30,
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '朝阳公园',
            city: '北京',
            placeName: '朝阳公园南门',
            point: { longitude: 116.471, latitude: 39.942 },
          },
          registeredCount: 25,
          tags: ['公益活动'],
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
          coverImage: null,
          feeAmount: 0.0,
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          capacity: 20,
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          registeredCount: 0,
          tags: ['学习交流'],
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
          coverImage: null,
          feeAmount: 0.0,
        },
        {
          activityId: '2005',
          title: '胡同骑行探索',
          capacity: 10,
          startAt: '2026-07-10T08:00:00Z',
          endAt: '2026-07-10T16:00:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          registeredCount: 10,
          tags: ['户外徒步', '运动健身'],
          reviewStatus: 'approved',
          runtimeStatus: 'ongoing',
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=5', mediaId: 'img2005' },
          feeAmount: 20.0,
        },
        {
          activityId: '2006',
          title: '中秋赏月诗词会',
          capacity: 25,
          startAt: '2026-06-15T19:00:00Z',
          endAt: '2026-06-15T22:00:00Z',
          location: {
            address: '上海浦东海滨公园',
            city: '上海',
            placeName: '滨海公园',
            point: { longitude: 121.606, latitude: 31.187 },
          },
          registeredCount: 25,
          tags: ['学习交流', '公益活动'],
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=6', mediaId: 'img2006' },
          feeAmount: 0.0,
        },
        {
          activityId: '2007',
          title: '违规活动（示例）',
          capacity: 50,
          startAt: '2026-08-01T10:00:00Z',
          endAt: '2026-08-01T18:00:00Z',
          location: {
            address: '示例地址',
            city: '北京',
            placeName: null,
            point: { longitude: 116.4, latitude: 39.9 },
          },
          registeredCount: 0,
          tags: [],
          reviewStatus: 'rejected',
          runtimeStatus: 'takenDown',
          coverImage: null,
          feeAmount: 0.0,
        },
      ],
      total: 7,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /*
   * 草稿 reviewStatus: draft | rejected
   */
  'GET /activities/drafts': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '3001',
          title: '（草稿）周末徒步香山',
          createdAt: '2026-06-28T10:00:00Z',
          updatedAt: '2026-06-30T22:00:00Z',
          reviewStatus: 'draft',
        },
        {
          activityId: '3002',
          title: '（草稿）摄影采风——颐和园',
          createdAt: '2026-07-01T09:00:00Z',
          updatedAt: '2026-07-01T09:00:00Z',
          reviewStatus: 'draft',
        },
        {
          activityId: '3003',
          title: '（已驳回）夜间登山活动',
          createdAt: '2026-06-20T15:00:00Z',
          updatedAt: '2026-06-21T10:00:00Z',
          reviewStatus: 'rejected',
        },
      ],
      total: 3,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 活动报名（我报名的活动） ===================== */

  /*
   * registrationStatus 全覆盖: registered | waiting | waitingConfirmation | canceled | checkedIn
   * runtimeStatus 覆盖率: registering | registrationClosed | ongoing | ended
   */
  'GET /activities/registrations/mine': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2001',
          title: '周末羽毛球友谊赛',
          tags: ['运动健身'],
          startAt: '2026-07-05T14:00:00Z',
          endAt: '2026-07-05T17:00:00Z',
          location: {
            address: '海淀区体育馆羽毛球馆',
            city: '北京',
            placeName: '海淀体育馆',
            point: { longitude: 116.347, latitude: 39.972 },
          },
          coverImage: null,
          feeAmount: 30.0,
          capacity: 16,
          registeredCount: 12,
          registrationId: 'r004',
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T12:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2010',
          title: '城市徒步——探寻胡同文化',
          tags: ['城市探索', '户外徒步'],
          startAt: '2026-07-08T08:30:00Z',
          endAt: '2026-07-08T11:30:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=101',
            mediaId: 'img2010',
          },
          feeAmount: 0,
          capacity: 20,
          registeredCount: 8,
          registrationId: '4001',
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T10:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2015',
          title: '公益环保志愿行',
          tags: ['公益活动'],
          startAt: '2026-06-22T07:00:00Z',
          endAt: '2026-06-22T12:00:00Z',
          location: {
            address: '朝阳区奥林匹克森林公园南门',
            city: '北京',
            placeName: '奥林匹克森林公园',
            point: { longitude: 116.391, latitude: 40.013 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 50,
          registeredCount: 35,
          registrationId: '4002',
          registrationStatus: 'checkedIn',
          registeredAt: '2026-06-20T12:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
        {
          activityId: '2020',
          title: '摄影采风——颐和园荷花季',
          tags: ['摄影采风'],
          startAt: '2026-07-15T06:00:00Z',
          endAt: '2026-07-15T10:00:00Z',
          location: {
            address: '海淀区颐和园东宫门',
            city: '北京',
            placeName: '颐和园',
            point: { longitude: 116.268, latitude: 39.998 },
          },
          coverImage: null,
          feeAmount: 15.0,
          capacity: 15,
          registeredCount: 5,
          registrationId: '4003',
          registrationStatus: 'canceled',
          registeredAt: '2026-06-15T14:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2025',
          title: '周末露营——海坨山谷',
          tags: ['户外徒步'],
          startAt: '2026-07-22T07:00:00Z',
          endAt: '2026-07-23T12:00:00Z',
          location: {
            address: '延庆区海坨山谷露营基地',
            city: '北京',
            placeName: '海坨山谷',
            point: { longitude: 115.815, latitude: 40.573 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=202',
            mediaId: 'img2025',
          },
          feeAmount: 299.0,
          capacity: 20,
          registeredCount: 20,
          registrationId: '4004',
          registrationStatus: 'waiting',
          registeredAt: '2026-07-01T10:00:00Z',
          waitingRank: 2,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2030',
          title: '室内攀岩体验日',
          tags: ['运动健身'],
          startAt: '2026-07-18T14:00:00Z',
          endAt: '2026-07-18T17:00:00Z',
          location: {
            address: '朝阳区攀岩馆（望京店）',
            city: '北京',
            placeName: '望京攀岩馆',
            point: { longitude: 116.478, latitude: 39.99 },
          },
          coverImage: null,
          feeAmount: 88.0,
          capacity: 12,
          registeredCount: 12,
          registrationId: '4005',
          registrationStatus: 'waitingConfirmation',
          registeredAt: '2026-07-02T08:00:00Z',
          waitingRank: 1,
          confirmationDeadline: '2026-07-18T10:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2005',
          title: '胡同骑行探索',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-10T08:00:00Z',
          endAt: '2026-07-10T16:00:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=5', mediaId: 'img2005' },
          feeAmount: 20.0,
          capacity: 10,
          registeredCount: 10,
          registrationId: '4006',
          registrationStatus: 'checkedIn',
          registeredAt: '2026-07-01T10:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'ongoing',
        },
        {
          activityId: '2002',
          title: '桌游之夜——三国杀专场',
          tags: ['桌游聚会'],
          startAt: '2026-07-12T19:00:00Z',
          endAt: '2026-07-12T22:00:00Z',
          location: {
            address: '五道口桌游吧',
            city: '北京',
            placeName: '五道口桌游吧',
            point: { longitude: 116.337, latitude: 39.982 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
          feeAmount: 50.0,
          capacity: 8,
          registeredCount: 8,
          registrationId: '4007',
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T09:00:00Z',
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
      ],
      total: 7,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 好友 ===================== */

  /*
   * source: manualRequest | mutualFollow
   * remark: 有 | 空
   * groupTags: 有 | 空 | 多标签
   */
  'GET /social/friends': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          userId: '10002',
          nickname: '小明',
          avatar: null,
          remark: '高中同学',
          groupTags: ['同学', '运动搭子'],
          source: 'mutualFollow',
        },
        {
          userId: '10003',
          nickname: '小红',
          avatar: { signedUrl: MOCK_IMAGE_BASE_URL + '/100?random=3', mediaId: 'img1002' },
          remark: '',
          groupTags: [],
          source: 'manualRequest',
        },
        {
          userId: '10004',
          nickname: '登山达人老李',
          avatar: null,
          remark: '户外领队',
          groupTags: ['户外', '领队', '周末搭子'],
          source: 'mutualFollow',
        },
      ],
      total: 3,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /*
   * source 全覆盖: profile | activityParticipants | team | qrCode
   * status: pending | accepted | rejected
   */
  'GET /social/friend-requests/received': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          requestId: '5001',
          requesterId: '10010',
          targetUserId: '10001',
          message: '你好，上次活动一起参加过',
          source: 'activityParticipants',
          status: 'pending',
          createdAt: '2026-07-01T10:00:00Z',
        },
        {
          requestId: '5002',
          requesterId: '10011',
          targetUserId: '10001',
          message: '',
          source: 'team',
          status: 'pending',
          createdAt: '2026-06-30T15:00:00Z',
        },
        {
          requestId: '5003',
          requesterId: '10012',
          targetUserId: '10001',
          message: '看了你的主页，想认识一下',
          source: 'profile',
          status: 'pending',
          createdAt: '2026-07-02T09:00:00Z',
        },
        {
          requestId: '5004',
          requesterId: '10013',
          targetUserId: '10001',
          message: '',
          source: 'qrCode',
          status: 'accepted',
          createdAt: '2026-06-25T12:00:00Z',
        },
        {
          requestId: '5005',
          requesterId: '10014',
          targetUserId: '10001',
          message: '加个好友吧',
          source: 'profile',
          status: 'rejected',
          createdAt: '2026-06-20T08:00:00Z',
        },
      ],
      total: 6,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  'GET /social/friend-requests/sent': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          requestId: '5101',
          requesterId: '10001',
          targetUserId: '10020',
          message: '通过小队认识的，加个好友吧',
          source: 'team',
          status: 'pending',
          createdAt: '2026-06-29T08:00:00Z',
        },
        {
          requestId: '5102',
          requesterId: '10001',
          targetUserId: '10021',
          message: '',
          source: 'activityParticipants',
          status: 'accepted',
          createdAt: '2026-06-22T14:00:00Z',
        },
        {
          requestId: '5103',
          requesterId: '10001',
          targetUserId: '10022',
          message: '你好',
          source: 'qrCode',
          status: 'rejected',
          createdAt: '2026-06-15T10:00:00Z',
        },
      ],
      total: 3,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /*
   * 黑名单：有 | 无 头像
   */
  'GET /social/blacklist': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          userId: '10099',
          nickname: '骚扰用户',
          avatar: null,
          blockedAt: '2026-06-15T12:00:00Z',
        },
        {
          userId: '10100',
          nickname: '广告推广号',
          avatar: { signedUrl: MOCK_IMAGE_BASE_URL + '/100?random=9', mediaId: 'img9901' },
          blockedAt: '2026-07-01T09:00:00Z',
        },
      ],
      total: 2,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 小队 ===================== */

  /*
   * joinMode: publicJoin | approvalRequired
   * status: active | dissolved
   * memberCount: 有 | 0
   * description: 有 | 空
   * avatar: 有 | 无
   */
  'GET /social/teams': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          teamId: '6001',
          name: '海淀桌游爱好者',
          description: '每周五组织线下桌游活动，欢迎加入！',
          tags: ['桌游聚会'],
          capacity: 50,
          memberCount: 23,
          leaderId: '10001',
          chatId: '7001',
          joinMode: 'publicJoin',
          status: 'active',
          avatar: { signedUrl: MOCK_IMAGE_BASE_URL + '/100?random=6', mediaId: 'img6001' },
        },
        {
          teamId: '6002',
          name: '户外徒步小分队',
          description: '周末京郊徒步，不定期组织',
          tags: ['户外徒步'],
          capacity: 30,
          memberCount: 18,
          leaderId: '10002',
          chatId: '7002',
          joinMode: 'approvalRequired',
          status: 'active',
          avatar: null,
        },
        {
          teamId: '6003',
          name: '新成立的摄影小组',
          description: '',
          tags: ['摄影采风'],
          capacity: 20,
          memberCount: 0,
          leaderId: '10003',
          chatId: '7003',
          joinMode: 'publicJoin',
          status: 'active',
          avatar: null,
        },
        {
          teamId: '6004',
          name: '已解散的读书会',
          description: '阅读分享与交流',
          tags: ['学习交流'],
          capacity: 15,
          memberCount: 5,
          leaderId: '10001',
          chatId: '7004',
          joinMode: 'approvalRequired',
          status: 'dissolved',
          avatar: null,
        },
      ],
      total: 4,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 社交资料 ===================== */

  /* 资料完整 */
  'GET /social/profiles/10002': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10002',
      nickname: '小明',
      avatar: { signedUrl: MOCK_IMAGE_BASE_URL + '/100?random=3', mediaId: 'img1002' },
      signature: '爱运动爱生活',
      interestTags: ['运动健身', '户外徒步'],
      gender: 'male',
      birthday: '1999-05-20',
      kind: 'personal',
      reputationScore: 95,
    },
  },

  /* 资料不完整（无签名、无性别、无生日） */
  'GET /social/profiles/10010': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      userId: '10010',
      nickname: '新用户001',
      avatar: null,
      signature: null,
      interestTags: [],
      gender: null,
      birthday: null,
      kind: 'personal',
      reputationScore: 50,
    },
  },

  /* ===================== 活动详情 ===================== */

  /*
   * 覆盖多种 runtimeStatus + 图片组合
   */
  'GET /activities/2001': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2001',
      title: '周末羽毛球友谊赛',
      tags: ['运动健身'],
      introduction:
        '周末一起来打羽毛球吧！无论你是初学者还是老手，都欢迎参加。' +
        '我们将根据水平分组，保证每个人都有愉快的体验。\n\n' +
        '活动流程：\n' +
        '1. 14:00 集合签到\n' +
        '2. 14:15 热身运动\n' +
        '3. 14:30 分组对抗\n' +
        '4. 16:30 自由交流\n' +
        '5. 17:00 结束\n\n' +
        '请自备球拍和运动装备，饮用水由组织者统一提供。',
      safetyNotice:
        '1. 运动前请充分热身，避免受伤。\n' +
        '2. 如有心脏病、高血压等不宜剧烈运动的疾病，请提前告知组织者。\n' +
        '3. 活动期间请保管好个人财物。\n' +
        '4. 建议穿着运动鞋和运动服装。\n' +
        '5. 如遇身体不适，请立即停止运动并联系组织者。',
      startAt: '2026-07-05T14:00:00Z',
      endAt: '2026-07-05T17:00:00Z',
      location: {
        address: '海淀区体育馆羽毛球馆',
        city: '北京',
        placeName: '海淀体育馆',
        point: { longitude: 116.347, latitude: 39.972 },
      },
      coverImage: null,
      images: [
        {
          mediaId: 'act_img_01',
          fileName: 'badminton_1.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 204800,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=10',
          uploadedAt: '2026-07-01T08:00:00Z',
        },
        {
          mediaId: 'act_img_02',
          fileName: 'badminton_2.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 153600,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=11',
          uploadedAt: '2026-07-01T08:00:00Z',
        },
        {
          mediaId: 'act_img_03',
          fileName: 'badminton_3.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 184320,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=12',
          uploadedAt: '2026-07-01T08:00:00Z',
        },
      ],
      feeAmount: 30.0,
      capacity: 16,
      registeredCount: 12,
      waitingCount: 0,
      registrationDeadline: '2026-07-04T23:59:59Z',
      organizerId: '10002',
      organizerName: '小明',
      reviewStatus: 'approved',
      runtimeStatus: 'registering',
      aiContentReview: {
        status: 'succeeded',
        riskLevel: 'low',
        suggestedReviewStatus: 'approved',
        reasons: [],
        friendlyErrorMessage: null,
      },
      manualReviewRequired: false,
      reviewRecords: [
        {
          reviewId: 'rev_001',
          result: 'approved',
          reason: null,
          reviewerId: 'system',
          reviewedAt: '2026-07-01T08:30:00Z',
        },
      ],
    },
  },

  'GET /activities/2001/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'registered',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: true,
      canConfirmWaitingSeat: false,
      canCheckIn: true,
      canReview: false,
    },
  },

  'GET /activities/2002': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2002',
      title: '桌游之夜——三国杀专场',
      tags: ['桌游聚会'],
      introduction:
        '每周一次的桌游之夜来啦！本期主题是三国杀，欢迎新老朋友参加。\n\n我们会准备多个扩展包，并有资深玩家现场教学。\n\n活动现场提供零食和饮料。',
      safetyNotice: '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。',
      startAt: '2026-07-12T19:00:00Z',
      endAt: '2026-07-12T22:00:00Z',
      location: {
        address: '五道口桌游吧',
        city: '北京',
        placeName: '五道口桌游吧',
        point: { longitude: 116.337, latitude: 39.982 },
      },
      coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
      images: [
        {
          mediaId: 'act_img_21',
          fileName: 'boardgame_1.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 184320,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=21',
          uploadedAt: '2026-07-01T09:00:00Z',
        },
        {
          mediaId: 'act_img_22',
          fileName: 'boardgame_2.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 204800,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=22',
          uploadedAt: '2026-07-01T09:00:00Z',
        },
      ],
      feeAmount: 50.0,
      capacity: 8,
      registeredCount: 8,
      waitingCount: 3,
      registrationDeadline: '2026-07-11T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'approved',
      runtimeStatus: 'registrationClosed',
      aiContentReview: {
        status: 'succeeded',
        riskLevel: 'low',
        suggestedReviewStatus: 'approved',
        reasons: [],
        friendlyErrorMessage: null,
      },
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2002/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'registered',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: true,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2005': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2005',
      title: '胡同骑行探索',
      tags: ['户外徒步', '运动健身'],
      introduction:
        '一起骑行探索北京胡同文化！从南锣鼓巷出发，途经北锣鼓巷、什刹海、烟袋斜街，最后回到出发点。全程约 15 公里，骑行时间约 3 小时。',
      safetyNotice: '请佩戴头盔等护具。遵守交通规则，注意避让行人。建议穿着长袖防晒。',
      startAt: '2026-07-10T08:00:00Z',
      endAt: '2026-07-10T16:00:00Z',
      location: {
        address: '东城区南锣鼓巷地铁站 E 口',
        city: '北京',
        placeName: '南锣鼓巷地铁站',
        point: { longitude: 116.403, latitude: 39.937 },
      },
      coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=5', mediaId: 'img2005' },
      images: [
        {
          mediaId: 'act_img_51',
          fileName: 'cycling_1.jpg',
          contentType: 'image/jpeg',
          sizeBytes: 256000,
          usage: 'activity',
          signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=51',
          uploadedAt: '2026-07-01T10:00:00Z',
        },
      ],
      feeAmount: 20.0,
      capacity: 10,
      registeredCount: 10,
      waitingCount: 0,
      registrationDeadline: '2026-07-09T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'approved',
      runtimeStatus: 'ongoing',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2005/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'checkedIn',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2010': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2010',
      title: '城市徒步——探寻胡同文化',
      tags: ['城市探索', '户外徒步'],
      introduction:
        '漫步北京胡同，感受老城历史韵味。' +
        '路线包括南锣鼓巷周边、什刹海、烟袋斜街等地，全程约 5 公里，徒步时间约 2 小时。',
      safetyNotice: '请穿着舒适的步行鞋。注意交通安全，过马路时遵守信号灯。建议携带饮用水。',
      startAt: '2026-07-08T08:30:00Z',
      endAt: '2026-07-08T11:30:00Z',
      location: {
        address: '东城区南锣鼓巷地铁站 E 口',
        city: '北京',
        placeName: '南锣鼓巷地铁站',
        point: { longitude: 116.403, latitude: 39.937 },
      },
      coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=101', mediaId: 'img2010' },
      images: [],
      feeAmount: 0,
      capacity: 20,
      registeredCount: 8,
      waitingCount: 0,
      registrationDeadline: '2026-07-07T23:59:59Z',
      organizerId: '10002',
      organizerName: '小明',
      reviewStatus: 'approved',
      runtimeStatus: 'registering',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2010/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'registered',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: true,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2015': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2015',
      title: '公益环保志愿行',
      tags: ['公益活动'],
      introduction:
        '加入我们的环保志愿团队，一起清理公园垃圾，宣传环保理念。' + '活动结束后有志愿者证书颁发。',
      safetyNotice:
        '请穿戴活动统一发放的马甲和手套。注意防晒，建议携带水杯。如有身体不适请及时告知领队。',
      startAt: '2026-06-22T07:00:00Z',
      endAt: '2026-06-22T12:00:00Z',
      location: {
        address: '朝阳区奥林匹克森林公园南门',
        city: '北京',
        placeName: '奥林匹克森林公园',
        point: { longitude: 116.391, latitude: 40.013 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0,
      capacity: 50,
      registeredCount: 35,
      waitingCount: 0,
      registrationDeadline: '2026-06-20T23:59:59Z',
      organizerId: '10005',
      organizerName: '绿色行动小组',
      reviewStatus: 'approved',
      runtimeStatus: 'ended',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2015/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'checkedIn',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2020': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2020',
      title: '摄影采风——颐和园荷花季',
      tags: ['摄影采风'],
      introduction:
        '颐和园荷花盛开季节，一起采风拍摄！' +
        '资深摄影师带队，分享构图和用光技巧。器材不限，手机也可参加。',
      safetyNotice: '水域附近注意安全，请勿翻越护栏。注意防晒和防蚊。',
      startAt: '2026-07-15T06:00:00Z',
      endAt: '2026-07-15T10:00:00Z',
      location: {
        address: '海淀区颐和园东宫门',
        city: '北京',
        placeName: '颐和园',
        point: { longitude: 116.268, latitude: 39.998 },
      },
      coverImage: null,
      images: [],
      feeAmount: 15.0,
      capacity: 15,
      registeredCount: 5,
      waitingCount: 0,
      registrationDeadline: '2026-07-14T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'approved',
      runtimeStatus: 'registering',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2020/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: true,
      status: 'canceled',
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2025': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2025',
      title: '周末露营——海坨山谷',
      tags: ['户外徒步'],
      introduction:
        '两天一夜的海坨山谷露营之旅！包含装备租赁、烧烤晚餐和早餐。' +
        '夜晚观星，晨间看日出，体验大自然的魅力。',
      safetyNotice:
        '山区气温较低，请携带保暖衣物和雨具。夜间注意防寒。' +
        '听从领队安排，不要擅自离队。建议购买户外保险。',
      startAt: '2026-07-22T07:00:00Z',
      endAt: '2026-07-23T12:00:00Z',
      location: {
        address: '延庆区海坨山谷露营基地',
        city: '北京',
        placeName: '海坨山谷',
        point: { longitude: 115.815, latitude: 40.573 },
      },
      coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=202', mediaId: 'img2025' },
      images: [],
      feeAmount: 299.0,
      capacity: 20,
      registeredCount: 20,
      waitingCount: 5,
      registrationDeadline: '2026-07-20T23:59:59Z',
      organizerId: '10003',
      organizerName: '小红',
      reviewStatus: 'approved',
      runtimeStatus: 'registrationClosed',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2025/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'waiting',
      waitingRank: 2,
      confirmationDeadline: null,
      canCancelRegistration: true,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2030': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2030',
      title: '室内攀岩体验日',
      tags: ['运动健身'],
      introduction:
        '专业攀岩馆体验活动，有教练指导，零基础也可以参加。' +
        '包含装备租赁和基础教学。挑战自我，感受攀岩的乐趣！',
      safetyNotice:
        '请穿着运动服装和运动鞋。攀岩前请认真听取安全讲解。' + '有恐高症或相关疾病请提前告知教练。',
      startAt: '2026-07-18T14:00:00Z',
      endAt: '2026-07-18T17:00:00Z',
      location: {
        address: '朝阳区攀岩馆（望京店）',
        city: '北京',
        placeName: '望京攀岩馆',
        point: { longitude: 116.478, latitude: 39.99 },
      },
      coverImage: null,
      images: [],
      feeAmount: 88.0,
      capacity: 12,
      registeredCount: 12,
      waitingCount: 3,
      registrationDeadline: '2026-07-17T23:59:59Z',
      organizerId: '10004',
      organizerName: '登山达人老李',
      reviewStatus: 'approved',
      runtimeStatus: 'registrationClosed',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2030/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: 'waitingConfirmation',
      waitingRank: 1,
      confirmationDeadline: '2026-07-18T10:00:00Z',
      canCancelRegistration: false,
      canConfirmWaitingSeat: true,
      canCheckIn: false,
      canReview: false,
    },
  },

  /* ===================== 活动草稿 ===================== */

  'POST /activities/drafts': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3100',
      title: '（新草稿）',
      tags: [],
      introduction: null,
      startAt: null,
      endAt: null,
      location: null,
      safetyNotice: null,
      capacity: null,
      registrationDeadline: null,
      feeAmount: null,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3001': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3001',
      title: '（草稿）周末徒步香山',
      tags: ['户外徒步', '运动健身'],
      introduction: '计划组织一次香山徒步活动，欢迎大家参加。具体路线和时间待定。',
      startAt: '2026-07-20T08:00:00Z',
      endAt: '2026-07-20T12:00:00Z',
      location: {
        address: '海淀区香山公园东门',
        city: '北京',
        placeName: '香山公园',
        point: { longitude: 116.207, latitude: 39.993 },
      },
      safetyNotice: '请穿着适合徒步的鞋子，自备饮用水。',
      capacity: 15,
      registrationDeadline: '2026-07-19T23:59:59Z',
      feeAmount: 0,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: '2026-06-30T22:00:00Z',
      createdAt: '2026-06-28T10:00:00Z',
    },
  },

  'PUT /activities/drafts/3001': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3001',
      title: '（草稿）周末徒步香山',
      tags: ['户外徒步', '运动健身'],
      introduction: '计划组织一次香山徒步活动，欢迎大家参加。具体路线和时间待定。',
      startAt: '2026-07-20T08:00:00Z',
      endAt: '2026-07-20T12:00:00Z',
      location: {
        address: '海淀区香山公园东门',
        city: '北京',
        placeName: '香山公园',
        point: { longitude: 116.207, latitude: 39.993 },
      },
      safetyNotice: '请穿着适合徒步的鞋子，自备饮用水。',
      capacity: 15,
      registrationDeadline: '2026-07-19T23:59:59Z',
      feeAmount: 0,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: '2026-06-28T10:00:00Z',
    },
  },

  'GET /activities/drafts/3100': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3100',
      title: '（新草稿）',
      tags: [],
      introduction: null,
      startAt: null,
      endAt: null,
      location: null,
      safetyNotice: null,
      capacity: null,
      registrationDeadline: null,
      feeAmount: null,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  /* 模板生成的草稿 */
  'GET /activities/drafts/tpl-draft-01': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: 'tpl-draft-01',
      title: '运动健身活动',
      tags: ['运动健身'],
      introduction: [
        '一起来运动吧！无论你是初学者还是老手，都欢迎参加。\n\n',
        '活动流程：\n1. 集合签到\n2. 热身运动\n3. 分组活动\n4. 自由交流\n5. 结束\n\n',
        '请自备装备，饮用水由组织者统一提供。',
      ].join(''),
      safetyNotice:
        '运动前请充分热身，避免受伤。如有心脏病、高血压等不宜剧烈运动的疾病，请提前告知组织者。活动期间请保管好个人财物。',
      capacity: 20,
      location: null,
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: null,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/tpl-draft-02': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: 'tpl-draft-02',
      title: '桌游聚会',
      tags: ['桌游聚会'],
      introduction:
        '桌游之夜来啦！欢迎新老朋友参加。\n\n我们会准备多种桌游，并有资深玩家现场教学。\n\n活动现场提供零食和饮料。',
      safetyNotice:
        '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。未成年人请在监护人陪同下参加。',
      capacity: 8,
      location: null,
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: null,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  /* 克隆生成的草稿 */
  'GET /activities/drafts/3101': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3101',
      title: '周末羽毛球友谊赛（副本）',
      tags: ['运动健身'],
      introduction: '周末一起来打羽毛球吧！无论你是初学者还是老手，都欢迎参加。',
      safetyNotice: '运动前请充分热身，避免受伤。',
      location: {
        address: '海淀区体育馆羽毛球馆',
        city: '北京',
        placeName: '海淀体育馆',
        point: { longitude: 116.347, latitude: 39.972 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 30.0,
      feeDescription: null,
      capacity: 16,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3102': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3102',
      title: '胡同骑行探索（副本）',
      tags: ['户外徒步', '运动健身'],
      introduction: '一起骑行探索北京胡同文化！从南锣鼓巷出发，途经北锣鼓巷、什刹海、烟袋斜街。',
      safetyNotice: '请佩戴头盔等护具。遵守交通规则，注意避让行人。',
      location: {
        address: '东城区南锣鼓巷地铁站 E 口',
        city: '北京',
        placeName: '南锣鼓巷地铁站',
        point: { longitude: 116.403, latitude: 39.937 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 20.0,
      feeDescription: null,
      capacity: 10,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3103': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3103',
      title: '桌游之夜——三国杀专场（副本）',
      tags: ['桌游聚会'],
      introduction: '每周一次的桌游之夜来啦！本期主题是三国杀，欢迎新老朋友参加。',
      safetyNotice: '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。',
      location: {
        address: '五道口桌游吧',
        city: '北京',
        placeName: '五道口桌游吧',
        point: { longitude: 116.337, latitude: 39.982 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 50.0,
      feeDescription: null,
      capacity: 8,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3104': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3104',
      title: '公益植树活动（副本）',
      tags: ['公益活动'],
      introduction: '一年一度的公益植树活动来啦！一起为城市增添绿色。',
      safetyNotice: '请穿着适合户外活动的服装和鞋子。使用工具时注意安全。',
      location: {
        address: '朝阳公园',
        city: '北京',
        placeName: '朝阳公园南门',
        point: { longitude: 116.471, latitude: 39.942 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 30,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3105': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3105',
      title: '英语角——职场口语练习（副本）',
      tags: ['学习交流'],
      introduction: '每周一次的英语角活动，本期主题为职场口语。',
      safetyNotice: '公共场所请注意个人物品安全。',
      location: {
        address: '朝阳区三里屯 soho B 座 3 层',
        city: '北京',
        placeName: '三里屯共享会议室',
        point: { longitude: 116.454, latitude: 39.931 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 20,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/drafts/3106': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3106',
      title: '中秋赏月诗词会（副本）',
      tags: ['学习交流', '公益活动'],
      introduction: '中秋佳节，一起赏月吟诗！',
      safetyNotice: '夜间活动请注意安全，海边风大请携带外套。',
      location: {
        address: '上海浦东海滨公园',
        city: '上海',
        placeName: '滨海公园',
        point: { longitude: 121.606, latitude: 31.187 },
      },
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 25,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'PUT /activities/drafts/3100': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3100',
      title: '（已更新草稿）',
      tags: [],
      introduction: null,
      startAt: null,
      endAt: null,
      location: null,
      safetyNotice: null,
      capacity: null,
      registrationDeadline: null,
      feeAmount: null,
      feeDescription: null,
      minAge: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/3100/submit': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3100',
      title: '新活动',
      tags: [],
      introduction: null,
      startAt: null,
      endAt: null,
      location: null,
      coverImage: null,
      images: [],
      feeAmount: null,
      capacity: 0,
      registeredCount: 0,
      waitingCount: 0,
      registrationDeadline: null,
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'pending',
      runtimeStatus: 'notStarted',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'POST /activities/3001/submit': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3001',
      title: '周末徒步香山',
      tags: ['户外徒步', '运动健身'],
      introduction: '计划组织一次香山徒步活动，欢迎大家参加。具体路线和时间待定。',
      startAt: '2026-07-20T08:00:00Z',
      endAt: '2026-07-20T12:00:00Z',
      location: {
        address: '海淀区香山公园东门',
        city: '北京',
        placeName: '香山公园',
        point: { longitude: 116.207, latitude: 39.993 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0,
      capacity: 15,
      registeredCount: 0,
      waitingCount: 0,
      registrationDeadline: '2026-07-19T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'pending',
      runtimeStatus: 'notStarted',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'POST /activities/media/images': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      mediaId: 'act_img_new',
      fileName: 'activity_upload.jpg',
      contentType: 'image/jpeg',
      sizeBytes: 204800,
      usage: 'activityImage',
      signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=upload',
      uploadedAt: new Date().toISOString(),
    },
  },

  'GET /activities/2003': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2003',
      title: '公益植树活动',
      tags: ['公益活动'],
      introduction:
        '一年一度的公益植树活动来啦！一起为城市增添绿色。\n\n' +
        '活动提供树苗和工具，你只需要带着热情来参加！\n\n' +
        '活动流程：\n' +
        '1. 8:00 集合签到\n' +
        '2. 8:30 植树教学\n' +
        '3. 9:00-11:00 植树\n' +
        '4. 11:00-12:00 合影与交流',
      safetyNotice:
        '请穿着适合户外活动的服装和鞋子。注意防晒，自备饮用水。' +
        '使用工具时注意安全，听从工作人员指导。',
      startAt: '2026-07-20T08:00:00Z',
      endAt: '2026-07-20T12:00:00Z',
      location: {
        address: '朝阳公园',
        city: '北京',
        placeName: '朝阳公园南门',
        point: { longitude: 116.471, latitude: 39.942 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0,
      capacity: 30,
      registeredCount: 25,
      waitingCount: 0,
      registrationDeadline: '2026-07-19T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'approved',
      runtimeStatus: 'registering',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2003/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: null,
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2004': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2004',
      title: '英语角——职场口语练习',
      tags: ['学习交流'],
      introduction:
        '每周一次的英语角活动，本期主题为职场口语。\n\n' +
        '适合想要提升英语口语能力的职场人士。外教主持，分组讨论。',
      safetyNotice: '公共场所请注意个人物品安全。请尊重他人发言，保持友好讨论氛围。',
      startAt: '2026-07-25T19:00:00Z',
      endAt: '2026-07-25T21:00:00Z',
      location: {
        address: '朝阳区三里屯 soho B 座 3 层',
        city: '北京',
        placeName: '三里屯共享会议室',
        point: { longitude: 116.454, latitude: 39.931 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0,
      capacity: 20,
      registeredCount: 0,
      waitingCount: 0,
      registrationDeadline: '2026-07-24T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'pending',
      runtimeStatus: 'notStarted',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2004/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: null,
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2006': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2006',
      title: '中秋赏月诗词会',
      tags: ['学习交流', '公益活动'],
      introduction:
        '中秋佳节，一起赏月吟诗！\n\n' +
        '活动现场提供月饼和茶水，参加者可以自带诗词朗诵。' +
        '活动设有最佳朗诵奖和最佳创作奖。',
      safetyNotice: '夜间活动请注意安全，海边风大请携带外套。',
      startAt: '2026-06-15T19:00:00Z',
      endAt: '2026-06-15T22:00:00Z',
      location: {
        address: '上海浦东海滨公园',
        city: '上海',
        placeName: '滨海公园',
        point: { longitude: 121.606, latitude: 31.187 },
      },
      coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=6', mediaId: 'img2006' },
      images: [],
      feeAmount: 0,
      capacity: 25,
      registeredCount: 25,
      waitingCount: 0,
      registrationDeadline: '2026-06-14T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'approved',
      runtimeStatus: 'ended',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2006/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: null,
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  'GET /activities/2007': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2007',
      title: '违规活动（示例）',
      tags: [],
      introduction: '该活动因违规已被下架。',
      safetyNotice: '',
      startAt: '2026-08-01T10:00:00Z',
      endAt: '2026-08-01T18:00:00Z',
      location: {
        address: '示例地址',
        city: '北京',
        placeName: null,
        point: { longitude: 116.4, latitude: 39.9 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0,
      capacity: 50,
      registeredCount: 0,
      waitingCount: 0,
      registrationDeadline: '2026-07-31T23:59:59Z',
      organizerId: '10001',
      organizerName: '测试用户',
      reviewStatus: 'rejected',
      runtimeStatus: 'takenDown',
      aiContentReview: null,
      manualReviewRequired: false,
      reviewRecords: [],
    },
  },

  'GET /activities/2007/participation-state': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      canRegister: false,
      status: null,
      waitingRank: null,
      confirmationDeadline: null,
      canCancelRegistration: false,
      canConfirmWaitingSeat: false,
      canCheckIn: false,
      canReview: false,
    },
  },

  /* ===================== 参与者列表 ===================== */

  'GET /activities/2001/participants': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          registrationId: 'r001',
          userId: '10003',
          nickname: '小红',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T10:00:00Z',
        },
        {
          registrationId: 'r002',
          userId: '10004',
          nickname: '登山达人老李',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T11:00:00Z',
        },
        {
          registrationId: 'r003',
          userId: '10010',
          nickname: '新用户001',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-02T08:00:00Z',
        },
        {
          registrationId: 'r004',
          userId: '10001',
          nickname: '测试用户',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T12:00:00Z',
        },
      ],
      total: 4,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  'GET /activities/2002/participants': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          registrationId: 'r011',
          userId: '10003',
          nickname: '小红',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T09:00:00Z',
        },
        {
          registrationId: 'r012',
          userId: '10004',
          nickname: '登山达人老李',
          avatar: null,
          registrationStatus: 'registered',
          registeredAt: '2026-07-01T09:30:00Z',
        },
        {
          registrationId: 'r013',
          userId: '10010',
          nickname: '新用户001',
          avatar: null,
          registrationStatus: 'checkedIn',
          registeredAt: '2026-07-01T10:00:00Z',
          checkedInAt: '2026-07-12T19:15:00Z',
        },
        {
          registrationId: 'r014',
          userId: '10013',
          nickname: '摄影师小王',
          avatar: null,
          registrationStatus: 'canceled',
          registeredAt: '2026-07-01T12:00:00Z',
        },
      ],
      total: 4,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 评价/总结/签到管理 ===================== */

  'POST /activities/2001/reviews': {
    code: 200,
    message: 'For Super Earth!',
    data: {},
  },

  'POST /activities/2001/summaries': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      summaryId: 'sum001',
      activityId: '2001',
      title: '周末羽毛球友谊赛总结',
      content: '这是一次非常愉快的活动...',
      images: [],
      imageTags: [],
      createdAt: new Date().toISOString(),
    },
  },

  'GET /activities/2001/check-ins': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          registrationId: 'r001',
          userId: '10003',
          nickname: '小红',
          registrationStatus: 'registered',
        },
        {
          registrationId: 'r002',
          userId: '10004',
          nickname: '登山达人老李',
          registrationStatus: 'checkedIn',
          checkedInAt: '2026-07-05T14:15:00Z',
        },
        {
          registrationId: 'r003',
          userId: '10010',
          nickname: '新用户001',
          registrationStatus: 'registered',
        },
        {
          registrationId: 'r004',
          userId: '10001',
          nickname: '测试用户',
          registrationStatus: 'registered',
        },
      ],
      total: 4,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* ===================== 签到 ===================== */

  'POST /activities/2001/check-in-qrcode': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2001',
      qrCodeToken: 'CKIN-2001-A7X9K2M4',
      expiresAt: '2026-07-05T15:00:00Z',
    },
  },

  'POST /activities/2001/check-ins': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      registrationId: 'r001',
      userId: '10001',
      nickname: '测试用户',
      registrationStatus: 'checkedIn',
      checkedInAt: new Date().toISOString(),
    },
  },

  'POST /activities/2005/check-in-qrcode': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '2005',
      qrCodeToken: 'CKIN-2005-B3Y5W7P9',
      expiresAt: '2026-07-10T10:00:00Z',
    },
  },

  'POST /activities/2005/check-ins': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      registrationId: 'r051',
      userId: '10001',
      nickname: '测试用户',
      registrationStatus: 'checkedIn',
      checkedInAt: new Date().toISOString(),
    },
  },

  /* ===================== 首页信息流 ===================== */

  /**
   * 首页活动信息流 —— 推荐 tab
   *
   * 返回推荐活动列表，覆盖多种标签/费用/运行时状态。
   */
  'GET /activities/feed?tab=recommended&page=1&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2001',
          title: '周末羽毛球友谊赛',
          tags: ['运动健身'],
          startAt: '2026-07-05T14:00:00Z',
          endAt: '2026-07-05T17:00:00Z',
          location: {
            address: '海淀区体育馆羽毛球馆',
            city: '北京',
            placeName: '海淀体育馆',
            point: { longitude: 116.347, latitude: 39.972 },
          },
          coverImage: null,
          feeAmount: 30.0,
          capacity: 16,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2002',
          title: '桌游之夜——三国杀专场',
          tags: ['桌游聚会'],
          startAt: '2026-07-12T19:00:00Z',
          endAt: '2026-07-12T22:00:00Z',
          location: {
            address: '五道口桌游吧',
            city: '北京',
            placeName: '五道口桌游吧',
            point: { longitude: 116.337, latitude: 39.982 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
          feeAmount: 50.0,
          capacity: 8,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2003',
          title: '公益植树活动',
          tags: ['公益活动'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '朝阳公园',
            city: '北京',
            placeName: '朝阳公园南门',
            point: { longitude: 116.471, latitude: 39.942 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 30,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2010',
          title: '城市徒步——探寻胡同文化',
          tags: ['城市探索', '户外徒步'],
          startAt: '2026-07-08T08:30:00Z',
          endAt: '2026-07-08T11:30:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=101',
            mediaId: 'img2010',
          },
          feeAmount: 0,
          capacity: 20,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2020',
          title: '摄影采风——颐和园荷花季',
          tags: ['摄影采风'],
          startAt: '2026-07-15T06:00:00Z',
          endAt: '2026-07-15T10:00:00Z',
          location: {
            address: '海淀区颐和园东宫门',
            city: '北京',
            placeName: '颐和园',
            point: { longitude: 116.268, latitude: 39.998 },
          },
          coverImage: null,
          feeAmount: 15.0,
          capacity: 15,
          registeredCount: 5,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2005',
          title: '胡同骑行探索',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-10T08:00:00Z',
          endAt: '2026-07-10T16:00:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=5', mediaId: 'img2005' },
          feeAmount: 20.0,
          capacity: 10,
          registeredCount: 10,
          reviewStatus: 'approved',
          runtimeStatus: 'ongoing',
        },
        {
          activityId: '2030',
          title: '室内攀岩体验日',
          tags: ['运动健身'],
          startAt: '2026-07-18T14:00:00Z',
          endAt: '2026-07-18T17:00:00Z',
          location: {
            address: '朝阳区攀岩馆（望京店）',
            city: '北京',
            placeName: '望京攀岩馆',
            point: { longitude: 116.478, latitude: 39.99 },
          },
          coverImage: null,
          feeAmount: 88.0,
          capacity: 12,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2025',
          title: '周末露营——海坨山谷',
          tags: ['户外徒步'],
          startAt: '2026-07-22T07:00:00Z',
          endAt: '2026-07-23T12:00:00Z',
          location: {
            address: '延庆区海坨山谷露营基地',
            city: '北京',
            placeName: '海坨山谷',
            point: { longitude: 115.815, latitude: 40.573 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=202',
            mediaId: 'img2025',
          },
          feeAmount: 299.0,
          capacity: 20,
          registeredCount: 20,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          tags: ['学习交流'],
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 20,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
        {
          activityId: '2015',
          title: '公益环保志愿行',
          tags: ['公益活动'],
          startAt: '2026-06-22T07:00:00Z',
          endAt: '2026-06-22T12:00:00Z',
          location: {
            address: '朝阳区奥林匹克森林公园南门',
            city: '北京',
            placeName: '奥林匹克森林公园',
            point: { longitude: 116.391, latitude: 40.013 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 50,
          registeredCount: 35,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
      ],
      total: 14,
      page: 1,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=recommended&page=2&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2006',
          title: '中秋赏月诗词会',
          tags: ['学习交流', '公益活动'],
          startAt: '2026-06-15T19:00:00Z',
          endAt: '2026-06-15T22:00:00Z',
          location: {
            address: '上海浦东海滨公园',
            city: '上海',
            placeName: '滨海公园',
            point: { longitude: 121.606, latitude: 31.187 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=6', mediaId: 'img2006' },
          feeAmount: 0.0,
          capacity: 25,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
        {
          activityId: '3001',
          title: '周末徒步香山',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '海淀区香山公园东门',
            city: '北京',
            placeName: '香山公园',
            point: { longitude: 116.207, latitude: 39.993 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 15,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
        {
          activityId: '2007',
          title: '（已下架示例）违规活动',
          tags: [],
          startAt: '2026-08-01T10:00:00Z',
          endAt: '2026-08-01T18:00:00Z',
          location: {
            address: '示例地址',
            city: '北京',
            placeName: null,
            point: { longitude: 116.4, latitude: 39.9 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 50,
          registeredCount: 0,
          reviewStatus: 'rejected',
          runtimeStatus: 'takenDown',
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          tags: ['学习交流'],
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 20,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
      ],
      total: 14,
      page: 2,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=recommended&page=3&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [],
      total: 14,
      page: 3,
      pageSize: 10,
      totalPages: 2,
    },
  },

  /** 首页信息流 —— 最新 tab */
  'GET /activities/feed?tab=latest&page=1&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2010',
          title: '城市徒步——探寻胡同文化',
          tags: ['城市探索', '户外徒步'],
          startAt: '2026-07-08T08:30:00Z',
          endAt: '2026-07-08T11:30:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=101',
            mediaId: 'img2010',
          },
          feeAmount: 0,
          capacity: 20,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2001',
          title: '周末羽毛球友谊赛',
          tags: ['运动健身'],
          startAt: '2026-07-05T14:00:00Z',
          endAt: '2026-07-05T17:00:00Z',
          location: {
            address: '海淀区体育馆羽毛球馆',
            city: '北京',
            placeName: '海淀体育馆',
            point: { longitude: 116.347, latitude: 39.972 },
          },
          coverImage: null,
          feeAmount: 30.0,
          capacity: 16,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2003',
          title: '公益植树活动',
          tags: ['公益活动'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '朝阳公园',
            city: '北京',
            placeName: '朝阳公园南门',
            point: { longitude: 116.471, latitude: 39.942 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 30,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2020',
          title: '摄影采风——颐和园荷花季',
          tags: ['摄影采风'],
          startAt: '2026-07-15T06:00:00Z',
          endAt: '2026-07-15T10:00:00Z',
          location: {
            address: '海淀区颐和园东宫门',
            city: '北京',
            placeName: '颐和园',
            point: { longitude: 116.268, latitude: 39.998 },
          },
          coverImage: null,
          feeAmount: 15.0,
          capacity: 15,
          registeredCount: 5,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          tags: ['学习交流'],
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 20,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
        {
          activityId: '2005',
          title: '胡同骑行探索',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-10T08:00:00Z',
          endAt: '2026-07-10T16:00:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=5', mediaId: 'img2005' },
          feeAmount: 20.0,
          capacity: 10,
          registeredCount: 10,
          reviewStatus: 'approved',
          runtimeStatus: 'ongoing',
        },
        {
          activityId: '2030',
          title: '室内攀岩体验日',
          tags: ['运动健身'],
          startAt: '2026-07-18T14:00:00Z',
          endAt: '2026-07-18T17:00:00Z',
          location: {
            address: '朝阳区攀岩馆（望京店）',
            city: '北京',
            placeName: '望京攀岩馆',
            point: { longitude: 116.478, latitude: 39.99 },
          },
          coverImage: null,
          feeAmount: 88.0,
          capacity: 12,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2025',
          title: '周末露营——海坨山谷',
          tags: ['户外徒步'],
          startAt: '2026-07-22T07:00:00Z',
          endAt: '2026-07-23T12:00:00Z',
          location: {
            address: '延庆区海坨山谷露营基地',
            city: '北京',
            placeName: '海坨山谷',
            point: { longitude: 115.815, latitude: 40.573 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=202',
            mediaId: 'img2025',
          },
          feeAmount: 299.0,
          capacity: 20,
          registeredCount: 20,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2002',
          title: '桌游之夜——三国杀专场',
          tags: ['桌游聚会'],
          startAt: '2026-07-12T19:00:00Z',
          endAt: '2026-07-12T22:00:00Z',
          location: {
            address: '五道口桌游吧',
            city: '北京',
            placeName: '五道口桌游吧',
            point: { longitude: 116.337, latitude: 39.982 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
          feeAmount: 50.0,
          capacity: 8,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2015',
          title: '公益环保志愿行',
          tags: ['公益活动'],
          startAt: '2026-06-22T07:00:00Z',
          endAt: '2026-06-22T12:00:00Z',
          location: {
            address: '朝阳区奥林匹克森林公园南门',
            city: '北京',
            placeName: '奥林匹克森林公园',
            point: { longitude: 116.391, latitude: 40.013 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 50,
          registeredCount: 35,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
      ],
      total: 14,
      page: 1,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=latest&page=2&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2006',
          title: '中秋赏月诗词会',
          tags: ['学习交流', '公益活动'],
          startAt: '2026-06-15T19:00:00Z',
          endAt: '2026-06-15T22:00:00Z',
          location: {
            address: '上海浦东海滨公园',
            city: '上海',
            placeName: '滨海公园',
            point: { longitude: 121.606, latitude: 31.187 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=6', mediaId: 'img2006' },
          feeAmount: 0.0,
          capacity: 25,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
        {
          activityId: '3001',
          title: '周末徒步香山',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '海淀区香山公园东门',
            city: '北京',
            placeName: '香山公园',
            point: { longitude: 116.207, latitude: 39.993 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 15,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
        {
          activityId: '2007',
          title: '（已下架示例）违规活动',
          tags: [],
          startAt: '2026-08-01T10:00:00Z',
          endAt: '2026-08-01T18:00:00Z',
          location: {
            address: '示例地址',
            city: '北京',
            placeName: null,
            point: { longitude: 116.4, latitude: 39.9 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 50,
          registeredCount: 0,
          reviewStatus: 'rejected',
          runtimeStatus: 'takenDown',
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          tags: ['学习交流'],
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 20,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
      ],
      total: 14,
      page: 2,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=latest&page=3&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [],
      total: 14,
      page: 3,
      pageSize: 10,
      totalPages: 2,
    },
  },

  /** 首页信息流 —— 附近 tab */
  'GET /activities/feed?tab=nearby&page=1&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2001',
          title: '周末羽毛球友谊赛',
          tags: ['运动健身'],
          startAt: '2026-07-05T14:00:00Z',
          endAt: '2026-07-05T17:00:00Z',
          location: {
            address: '海淀区体育馆羽毛球馆',
            city: '北京',
            placeName: '海淀体育馆',
            point: { longitude: 116.347, latitude: 39.972 },
          },
          coverImage: null,
          feeAmount: 30.0,
          capacity: 16,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2010',
          title: '城市徒步——探寻胡同文化',
          tags: ['城市探索', '户外徒步'],
          startAt: '2026-07-08T08:30:00Z',
          endAt: '2026-07-08T11:30:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=101',
            mediaId: 'img2010',
          },
          feeAmount: 0,
          capacity: 20,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2003',
          title: '公益植树活动',
          tags: ['公益活动'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '朝阳公园',
            city: '北京',
            placeName: '朝阳公园南门',
            point: { longitude: 116.471, latitude: 39.942 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 30,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2005',
          title: '胡同骑行探索',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-10T08:00:00Z',
          endAt: '2026-07-10T16:00:00Z',
          location: {
            address: '东城区南锣鼓巷地铁站 E 口',
            city: '北京',
            placeName: '南锣鼓巷地铁站',
            point: { longitude: 116.403, latitude: 39.937 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=5', mediaId: 'img2005' },
          feeAmount: 20.0,
          capacity: 10,
          registeredCount: 10,
          reviewStatus: 'approved',
          runtimeStatus: 'ongoing',
        },
        {
          activityId: '2002',
          title: '桌游之夜——三国杀专场',
          tags: ['桌游聚会'],
          startAt: '2026-07-12T19:00:00Z',
          endAt: '2026-07-12T22:00:00Z',
          location: {
            address: '五道口桌游吧',
            city: '北京',
            placeName: '五道口桌游吧',
            point: { longitude: 116.337, latitude: 39.982 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=2', mediaId: 'img2002' },
          feeAmount: 50.0,
          capacity: 8,
          registeredCount: 8,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2020',
          title: '摄影采风——颐和园荷花季',
          tags: ['摄影采风'],
          startAt: '2026-07-15T06:00:00Z',
          endAt: '2026-07-15T10:00:00Z',
          location: {
            address: '海淀区颐和园东宫门',
            city: '北京',
            placeName: '颐和园',
            point: { longitude: 116.268, latitude: 39.998 },
          },
          coverImage: null,
          feeAmount: 15.0,
          capacity: 15,
          registeredCount: 5,
          reviewStatus: 'approved',
          runtimeStatus: 'registering',
        },
        {
          activityId: '2030',
          title: '室内攀岩体验日',
          tags: ['运动健身'],
          startAt: '2026-07-18T14:00:00Z',
          endAt: '2026-07-18T17:00:00Z',
          location: {
            address: '朝阳区攀岩馆（望京店）',
            city: '北京',
            placeName: '望京攀岩馆',
            point: { longitude: 116.478, latitude: 39.99 },
          },
          coverImage: null,
          feeAmount: 88.0,
          capacity: 12,
          registeredCount: 12,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2004',
          title: '英语角——职场口语练习',
          tags: ['学习交流'],
          startAt: '2026-07-25T19:00:00Z',
          endAt: '2026-07-25T21:00:00Z',
          location: {
            address: '朝阳区三里屯 soho B 座 3 层',
            city: '北京',
            placeName: '三里屯共享会议室',
            point: { longitude: 116.454, latitude: 39.931 },
          },
          coverImage: null,
          feeAmount: 0.0,
          capacity: 20,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
        {
          activityId: '2025',
          title: '周末露营——海坨山谷',
          tags: ['户外徒步'],
          startAt: '2026-07-22T07:00:00Z',
          endAt: '2026-07-23T12:00:00Z',
          location: {
            address: '延庆区海坨山谷露营基地',
            city: '北京',
            placeName: '海坨山谷',
            point: { longitude: 115.815, latitude: 40.573 },
          },
          coverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=202',
            mediaId: 'img2025',
          },
          feeAmount: 299.0,
          capacity: 20,
          registeredCount: 20,
          reviewStatus: 'approved',
          runtimeStatus: 'registrationClosed',
        },
        {
          activityId: '2015',
          title: '公益环保志愿行',
          tags: ['公益活动'],
          startAt: '2026-06-22T07:00:00Z',
          endAt: '2026-06-22T12:00:00Z',
          location: {
            address: '朝阳区奥林匹克森林公园南门',
            city: '北京',
            placeName: '奥林匹克森林公园',
            point: { longitude: 116.391, latitude: 40.013 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 50,
          registeredCount: 35,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
      ],
      total: 12,
      page: 1,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=nearby&page=2&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          activityId: '2006',
          title: '中秋赏月诗词会',
          tags: ['学习交流', '公益活动'],
          startAt: '2026-06-15T19:00:00Z',
          endAt: '2026-06-15T22:00:00Z',
          location: {
            address: '上海浦东海滨公园',
            city: '上海',
            placeName: '滨海公园',
            point: { longitude: 121.606, latitude: 31.187 },
          },
          coverImage: { signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=6', mediaId: 'img2006' },
          feeAmount: 0.0,
          capacity: 25,
          registeredCount: 25,
          reviewStatus: 'approved',
          runtimeStatus: 'ended',
        },
        {
          activityId: '3001',
          title: '周末徒步香山',
          tags: ['户外徒步', '运动健身'],
          startAt: '2026-07-20T08:00:00Z',
          endAt: '2026-07-20T12:00:00Z',
          location: {
            address: '海淀区香山公园东门',
            city: '北京',
            placeName: '香山公园',
            point: { longitude: 116.207, latitude: 39.993 },
          },
          coverImage: null,
          feeAmount: 0,
          capacity: 15,
          registeredCount: 0,
          reviewStatus: 'pending',
          runtimeStatus: 'notStarted',
        },
      ],
      total: 12,
      page: 2,
      pageSize: 10,
      totalPages: 2,
    },
  },

  'GET /activities/feed?tab=nearby&page=3&pageSize=10': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [],
      total: 12,
      page: 3,
      pageSize: 10,
      totalPages: 2,
    },
  },

  /* ===================== 活动克隆 ===================== */

  'POST /activities/2001/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3101',
      title: '周末羽毛球友谊赛（副本）',
      tags: ['运动健身'],
      introduction: '周末一起来打羽毛球吧！无论你是初学者还是老手，都欢迎参加。',
      safetyNotice: '运动前请充分热身，避免受伤。',
      startAt: null,
      endAt: null,
      location: {
        address: '海淀区体育馆羽毛球馆',
        city: '北京',
        placeName: '海淀体育馆',
        point: { longitude: 116.347, latitude: 39.972 },
      },
      coverImage: null,
      images: [],
      feeAmount: 30.0,
      feeDescription: null,
      capacity: 16,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/2005/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3102',
      title: '胡同骑行探索（副本）',
      tags: ['户外徒步', '运动健身'],
      introduction: '一起骑行探索北京胡同文化！从南锣鼓巷出发，途经北锣鼓巷、什刹海、烟袋斜街。',
      safetyNotice: '请佩戴头盔等护具。遵守交通规则，注意避让行人。',
      startAt: null,
      endAt: null,
      location: {
        address: '东城区南锣鼓巷地铁站 E 口',
        city: '北京',
        placeName: '南锣鼓巷地铁站',
        point: { longitude: 116.403, latitude: 39.937 },
      },
      coverImage: null,
      images: [],
      feeAmount: 20.0,
      feeDescription: null,
      capacity: 10,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/2002/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3103',
      title: '桌游之夜——三国杀专场（副本）',
      tags: ['桌游聚会'],
      introduction: '每周一次的桌游之夜来啦！本期主题是三国杀，欢迎新老朋友参加。',
      safetyNotice: '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。',
      startAt: null,
      endAt: null,
      location: {
        address: '五道口桌游吧',
        city: '北京',
        placeName: '五道口桌游吧',
        point: { longitude: 116.337, latitude: 39.982 },
      },
      coverImage: null,
      images: [],
      feeAmount: 50.0,
      feeDescription: null,
      capacity: 8,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/2003/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3104',
      title: '公益植树活动（副本）',
      tags: ['公益活动'],
      introduction: '一年一度的公益植树活动来啦！一起为城市增添绿色。',
      safetyNotice: '请穿着适合户外活动的服装和鞋子。使用工具时注意安全。',
      startAt: null,
      endAt: null,
      location: {
        address: '朝阳公园',
        city: '北京',
        placeName: '朝阳公园南门',
        point: { longitude: 116.471, latitude: 39.942 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 30,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/2004/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3105',
      title: '英语角——职场口语练习（副本）',
      tags: ['学习交流'],
      introduction: '每周一次的英语角活动，本期主题为职场口语。',
      safetyNotice: '公共场所请注意个人物品安全。',
      startAt: null,
      endAt: null,
      location: {
        address: '朝阳区三里屯 soho B 座 3 层',
        city: '北京',
        placeName: '三里屯共享会议室',
        point: { longitude: 116.454, latitude: 39.931 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 20,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/2006/clone': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: '3106',
      title: '中秋赏月诗词会（副本）',
      tags: ['学习交流', '公益活动'],
      introduction: '中秋佳节，一起赏月吟诗！',
      safetyNotice: '夜间活动请注意安全，海边风大请携带外套。',
      startAt: null,
      endAt: null,
      location: {
        address: '上海浦东海滨公园',
        city: '上海',
        placeName: '滨海公园',
        point: { longitude: 121.606, latitude: 31.187 },
      },
      coverImage: null,
      images: [],
      feeAmount: 0.0,
      feeDescription: null,
      capacity: 25,
      registrationDeadline: null,
      minAge: null,
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  /* ===================== 活动模板 ===================== */

  'GET /activities/templates': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      items: [
        {
          templateId: 'tpl-01',
          name: '运动健身',
          activityType: 'sports',
          defaultTags: ['运动健身'],
          defaultIntroduction: [
            '一起来运动吧！无论你是初学者还是老手，都欢迎参加。\n\n',
            '活动流程：\n1. 集合签到\n2. 热身运动\n3. 分组活动\n4. 自由交流\n5. 结束\n\n',
            '请自备装备，饮用水由组织者统一提供。',
          ].join(''),
          defaultSafetyNotice:
            '运动前请充分热身，避免受伤。如有心脏病、高血压等不宜剧烈运动的疾病，请提前告知组织者。活动期间请保管好个人财物。',
          defaultCapacity: 20,
          defaultCoverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=tpl1',
            mediaId: 'tpl-img-01',
          },
        },
        {
          templateId: 'tpl-02',
          name: '桌游聚会',
          activityType: 'boardgame',
          defaultTags: ['桌游聚会'],
          defaultIntroduction:
            '桌游之夜来啦！欢迎新老朋友参加。\n\n我们会准备多种桌游，并有资深玩家现场教学。\n\n活动现场提供零食和饮料。',
          defaultSafetyNotice:
            '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。未成年人请在监护人陪同下参加。',
          defaultCapacity: 8,
          defaultCoverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=tpl2',
            mediaId: 'tpl-img-02',
          },
        },
        {
          templateId: 'tpl-03',
          name: '户外徒步',
          activityType: 'hiking',
          defaultTags: ['户外徒步'],
          defaultIntroduction:
            '一起徒步探索自然！\n\n路线包含城市步道和自然小径，全程约 5 公里，徒步时间约 2 小时。\n\n沿途风景优美，适合拍照打卡。',
          defaultSafetyNotice:
            '请穿着适合徒步的鞋子，自备饮用水和防晒用品。注意防蚊虫。听从领队安排，不要擅自离队。',
          defaultCapacity: 15,
          defaultCoverImage: {
            signedUrl: MOCK_IMAGE_BASE_URL + '/400/200?random=tpl3',
            mediaId: 'tpl-img-03',
          },
        },
        {
          templateId: 'tpl-04',
          name: '学习交流',
          activityType: 'learning',
          defaultTags: ['学习交流'],
          defaultIntroduction:
            '知识分享与交流活动。\n\n本期主题：待定\n\n适合所有对该主题感兴趣的朋友参加。',
          defaultSafetyNotice: '公共场所请注意个人物品安全。请尊重他人发言，保持友好讨论氛围。',
          defaultCapacity: 20,
          defaultCoverImage: null,
        },
        {
          templateId: 'tpl-05',
          name: '公益活动',
          activityType: 'charity',
          defaultTags: ['公益活动'],
          defaultIntroduction:
            '加入我们的公益活动，一起为社会贡献力量！\n\n活动提供所需工具和物资，你只需要带着热情来参加！',
          defaultSafetyNotice:
            '请穿着适合户外活动的服装和鞋子。使用工具时注意安全，听从工作人员指导。',
          defaultCapacity: 30,
          defaultCoverImage: null,
        },
      ],
      total: 5,
      page: 1,
      pageSize: 20,
      totalPages: 1,
    },
  },

  /* 基于模板创建草稿 */
  'POST /activities/templates/tpl-01/drafts': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: 'tpl-draft-01',
      title: '运动健身活动',
      tags: ['运动健身'],
      introduction: [
        '一起来运动吧！无论你是初学者还是老手，都欢迎参加。\n\n',
        '活动流程：\n1. 集合签到\n2. 热身运动\n3. 分组活动\n4. 自由交流\n5. 结束\n\n',
        '请自备装备，饮用水由组织者统一提供。',
      ].join(''),
      safetyNotice:
        '运动前请充分热身，避免受伤。如有心脏病、高血压等不宜剧烈运动的疾病，请提前告知组织者。活动期间请保管好个人财物。',
      capacity: 20,
      location: null,
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  'POST /activities/templates/tpl-02/drafts': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      activityId: 'tpl-draft-02',
      title: '桌游聚会',
      tags: ['桌游聚会'],
      introduction:
        '桌游之夜来啦！欢迎新老朋友参加。\n\n我们会准备多种桌游，并有资深玩家现场教学。\n\n活动现场提供零食和饮料。',
      safetyNotice:
        '请在公共场所注意个人物品安全。玩桌游时保持友好氛围，不要过度激动。未成年人请在监护人陪同下参加。',
      capacity: 8,
      location: null,
      startAt: null,
      endAt: null,
      registrationDeadline: null,
      feeAmount: null,
      images: [],
      reviewStatus: 'draft',
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  },

  /* ===================== 签到导出 ===================== */

  /* 签到导出返回二进制文件，mock 返回文本模拟 */
  'GET /activities/2001/check-ins/export': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      url: MOCK_IMAGE_BASE_URL + '/400/300?random=export',
    },
  },

  /* ===================== 评价图片上传 ===================== */

  'POST /activities/media/review-images': {
    code: 200,
    message: 'For Super Earth!',
    data: {
      mediaId: 'review-img-' + Date.now(),
      fileName: 'review_image.jpg',
      contentType: 'image/jpeg',
      sizeBytes: 204800,
      usage: 'activityReviewImage',
      signedUrl: MOCK_IMAGE_BASE_URL + '/800/400?random=' + Math.floor(Math.random() * 1000),
      uploadedAt: new Date().toISOString(),
    },
  },
}
