spring:
  datasource:
    url: jdbc:postgresql://${MAYOISTAR_DB_HOST:postgres}:${MAYOISTAR_DB_PORT:5432}/${POSTGRES_DB:mayoistar}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}

mayoistar:
  media:
    access:
      signing-secret: ${MAYOISTAR_MEDIA_SIGNING_SECRET}
